version: '3.8'

services:
  tomcat-server:
    build: ./
    ports:
      - "8080:8080"
    environment:
      # Environment variables accessible in your Tomcat application
      #DATABASE_URL: jdbc:postgresql://postgres-db:5432/mydb
      DATABASE_USER: myuser
      DATABASE_PASSWORD: mypassword
    depends_on:
      - postgres-db
    #volumes:
      # Optional: Mount a local directory to Tomcat's webapps for hot deployment
      # - ./webapps:/usr/local/tomcat/webapps

  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: warm-cat
    ports:
      - "5432:5432"
    volumes:
      # Persist PostgreSQL data even if the container is stopped/removed
      - postgres_data:/var/lib/postgresql/data
      # Optional: Mount your init.sql script to initialize the database
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: